-- MySQL Script generated by MySQL Workbench
-- Mon Apr 23 12:59:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`position` (
  `positionID` INT NOT NULL AUTO_INCREMENT,
  `positionName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`positionID`),
  UNIQUE INDEX `positionID_UNIQUE` (`positionID` ASC),
  UNIQUE INDEX `positionName_UNIQUE` (`positionName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `user_positionID` INT NOT NULL,
  `fName` VARCHAR(45) NOT NULL,
  `lName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `registerDate` DATE NOT NULL,
  `sessionID` VARCHAR(64) NULL,
  `lastLogin` DATETIME NULL,
  `adminID` BINARY(1) NOT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `positionID_idx` (`user_positionID` ASC),
  CONSTRAINT `user_positionID`
    FOREIGN KEY (`user_positionID`)
    REFERENCES `mydb`.`position` (`positionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`change_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`change_type` (
  `changeID` INT NOT NULL AUTO_INCREMENT,
  `changeType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`changeID`),
  UNIQUE INDEX `changeID_UNIQUE` (`changeID` ASC),
  UNIQUE INDEX `changeType_UNIQUE` (`changeType` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`system_change`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`system_change` (
  `join_userID` INT NOT NULL,
  `join_changeID` INT NOT NULL,
  `changeTime` DATETIME NOT NULL,
  INDEX `changeID_idx` (`join_changeID` ASC),
  PRIMARY KEY (`join_changeID`, `join_userID`),
  CONSTRAINT `join_userID`
    FOREIGN KEY (`join_userID`)
    REFERENCES `mydb`.`account` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `join_changeID`
    FOREIGN KEY (`join_changeID`)
    REFERENCES `mydb`.`change_type` (`changeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `customerID` INT NOT NULL AUTO_INCREMENT,
  `customerBusiness` VARCHAR(64) NOT NULL,
  `customerAddress1` VARCHAR(45) NOT NULL,
  `customerAddress2` VARCHAR(45) NOT NULL,
  `customerAddress3` VARCHAR(45) NULL,
  `customerCountry` VARCHAR(45) NOT NULL,
  `customerNumber` VARCHAR(45) NULL,
  `customerVAT` VARCHAR(45) NULL,
  `customerEmail` VARCHAR(45) NOT NULL,
  `customerEmailCC` VARCHAR(45) NULL,
  `customerPhone` VARCHAR(45) NULL,
  PRIMARY KEY (`customerID`),
  UNIQUE INDEX `customerID_UNIQUE` (`customerID` ASC),
  UNIQUE INDEX `customerBusiness_UNIQUE` (`customerBusiness` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`currency` (
  `currencyID` INT NOT NULL AUTO_INCREMENT,
  `currencyName` VARCHAR(45) NOT NULL,
  `currencyConvert` DECIMAL(5,5) NOT NULL,
  `validFrom` DATE NOT NULL,
  `validUntil` DATE NOT NULL,
  PRIMARY KEY (`currencyID`),
  UNIQUE INDEX `currencyID_UNIQUE` (`currencyID` ASC),
  UNIQUE INDEX `currencyName_UNIQUE` (`currencyName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vat` (
  `vatID` INT NOT NULL AUTO_INCREMENT,
  `vatRate` DECIMAL NOT NULL,
  PRIMARY KEY (`vatID`),
  UNIQUE INDEX `vatID_UNIQUE` (`vatID` ASC),
  UNIQUE INDEX `vatRate_UNIQUE` (`vatRate` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`invoice` (
  `invoiceNo` INT NOT NULL AUTO_INCREMENT,
  `invoice_customerID` INT NOT NULL,
  `invoice_userID` INT NOT NULL,
  `saleVoid` BINARY(1) NOT NULL,
  `invoiceDate` DATE NOT NULL,
  `invoiceDueDate` DATE NOT NULL,
  `invoice_vatID` INT NOT NULL,
  `invoiceVat` DECIMAL(6,2) NOT NULL,
  `invoiceAdjustments` DECIMAL(6,2) NOT NULL,
  `invoice_currencyID` INT NOT NULL,
  `invoiceSterling` DECIMAL(6,2) NOT NULL,
  `invoiceSterlingVat` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`invoiceNo`),
  UNIQUE INDEX `saleID_UNIQUE` (`invoiceNo` ASC),
  INDEX `userID_idx` (`invoice_userID` ASC),
  INDEX `customerID_idx` (`invoice_customerID` ASC),
  INDEX `currencyID_idx` (`invoice_currencyID` ASC),
  INDEX `vatID_idx` (`invoice_vatID` ASC),
  CONSTRAINT `invoice_userID`
    FOREIGN KEY (`invoice_userID`)
    REFERENCES `mydb`.`account` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `invoice_customerID`
    FOREIGN KEY (`invoice_customerID`)
    REFERENCES `mydb`.`customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `invoice_currencyID`
    FOREIGN KEY (`invoice_currencyID`)
    REFERENCES `mydb`.`currency` (`currencyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `invoice_vatID`
    FOREIGN KEY (`invoice_vatID`)
    REFERENCES `mydb`.`vat` (`vatID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `productID` INT NOT NULL AUTO_INCREMENT,
  `productCategory` VARCHAR(45) NOT NULL,
  `productPlatform` VARCHAR(45) NOT NULL,
  `productState` VARCHAR(45) NOT NULL,
  `productName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`productID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock` (
  `stockID` INT NOT NULL AUTO_INCREMENT,
  `quantityStock` INT NOT NULL,
  `priceBought` DECIMAL(5,2) NOT NULL,
  `stock_customerID` INT NOT NULL,
  `stock_currencyID` INT NOT NULL,
  `priceBoughtSterling` DECIMAL(5,2) NOT NULL,
  `stock_productID` INT NOT NULL,
  `boughtDate` DATE NOT NULL,
  PRIMARY KEY (`stockID`),
  UNIQUE INDEX `stockID_UNIQUE` (`stockID` ASC),
  INDEX `customerID_idx` (`stock_customerID` ASC),
  INDEX `currencyID_idx` (`stock_currencyID` ASC),
  INDEX `productID_idx` (`stock_productID` ASC),
  CONSTRAINT `stock_customerID`
    FOREIGN KEY (`stock_customerID`)
    REFERENCES `mydb`.`customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `stock_currencyID`
    FOREIGN KEY (`stock_currencyID`)
    REFERENCES `mydb`.`currency` (`currencyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `stock_productID`
    FOREIGN KEY (`stock_productID`)
    REFERENCES `mydb`.`product` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`credit_note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`credit_note` (
  `creditNo` INT NOT NULL AUTO_INCREMENT,
  `credit_customerID` INT NOT NULL,
  `credit_userID` INT NOT NULL,
  `creditDate` DATE NOT NULL,
  `creditDuedate` DATE NOT NULL,
  `credit_vatID` INT NOT NULL,
  `creditVat` DECIMAL(6,2) NOT NULL,
  `creditAdjustments` DECIMAL(6,2) NOT NULL,
  `credit_currencyID` INT NOT NULL,
  `creditSterling` DECIMAL(6,2) NOT NULL,
  `creditSterlingVat` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`creditNo`),
  UNIQUE INDEX `creditID_UNIQUE` (`creditNo` ASC),
  INDEX `customerID_idx` (`credit_customerID` ASC),
  INDEX `userID_idx` (`credit_userID` ASC),
  INDEX `currencyID  _idx` (`credit_currencyID` ASC),
  INDEX `vatID_idx` (`credit_vatID` ASC),
  CONSTRAINT `credit_customerID`
    FOREIGN KEY (`credit_customerID`)
    REFERENCES `mydb`.`customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `credit_userID`
    FOREIGN KEY (`credit_userID`)
    REFERENCES `mydb`.`account` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `credit_currencyID  `
    FOREIGN KEY (`credit_currencyID`)
    REFERENCES `mydb`.`currency` (`currencyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `credit_vatID`
    FOREIGN KEY (`credit_vatID`)
    REFERENCES `mydb`.`vat` (`vatID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`invoice_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`invoice_stock` (
  `join_invoiceNo` INT NOT NULL,
  `join_stockID` INT NOT NULL,
  `stockQuantity` INT NOT NULL,
  `priceSold` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`join_invoiceNo`, `join_stockID`),
  INDEX `stockID_idx` (`join_stockID` ASC),
  CONSTRAINT `join_invoiceNo`
    FOREIGN KEY (`join_invoiceNo`)
    REFERENCES `mydb`.`invoice` (`invoiceNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `join_stockID`
    FOREIGN KEY (`join_stockID`)
    REFERENCES `mydb`.`stock` (`stockID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`credit_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`credit_stock` (
  `join_creditNo` INT NOT NULL,
  `join_stockID` INT NOT NULL,
  `stockQuantity` INT NOT NULL,
  `priceCredit` DECIMAL(5,2) NOT NULL,
  INDEX `stockID_idx` (`join_stockID` ASC),
  PRIMARY KEY (`join_creditNo`, `join_stockID`),
  CONSTRAINT `join_creditNo`
    FOREIGN KEY (`join_creditNo`)
    REFERENCES `mydb`.`credit_note` (`creditNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `join_stockID`
    FOREIGN KEY (`join_stockID`)
    REFERENCES `mydb`.`stock` (`stockID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`offer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`offer` (
  `offerID` INT NOT NULL AUTO_INCREMENT,
  `offer_customerID` INT NOT NULL,
  `offer_productID` INT NOT NULL,
  `priceOffer` DECIMAL(5,2) NOT NULL,
  `offer_currencyID` INT NOT NULL,
  `quantityOffer` VARCHAR(45) NOT NULL,
  `dateOffer` DATETIME NOT NULL,
  `offerPriceSterling` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`offerID`),
  UNIQUE INDEX `offerID_UNIQUE` (`offerID` ASC),
  INDEX `customerID_idx` (`offer_customerID` ASC),
  INDEX `productID_idx` (`offer_productID` ASC),
  INDEX `currencyID_idx` (`offer_currencyID` ASC),
  CONSTRAINT `offer_customerID`
    FOREIGN KEY (`offer_customerID`)
    REFERENCES `mydb`.`customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `offer_productID`
    FOREIGN KEY (`offer_productID`)
    REFERENCES `mydb`.`product` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `offer_currencyID`
    FOREIGN KEY (`offer_currencyID`)
    REFERENCES `mydb`.`currency` (`currencyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
